graph TD;
        __start__([<p>__start__</p>]):::first
        model(model)
        tools(tools)
        HumanInTheLoopMiddleware\2eafter_model(HumanInTheLoopMiddleware.after_model)
        __end__([<p>__end__</p>]):::last
        HumanInTheLoopMiddleware\2eafter_model -.-> __end__;
        HumanInTheLoopMiddleware\2eafter_model -.-> model;
        HumanInTheLoopMiddleware\2eafter_model -.-> tools;
        __start__ --> model;
        model --> HumanInTheLoopMiddleware\2eafter_model;
        tools -.-> model;
        classDef default fill:#f2f0ff,line-height:1.2
        classDef first fill-opacity:0
        classDef last fill:#bfb6fc